spring:
  profiles:
    active: usage_message
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
logging:
  level:
    org: INFO

tutorial:
  client:
    duration: 10000
    
